# 파일 위치: .github/workflows/pelican.yml

name: Pelican CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Configure Git Safe Directory for Output
        run: |
          git config --global --add safe.directory "${{ github.workspace }}/output"
          git config --global --add safe.directory "${{ github.workspace }}" 


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt


      - name: Build Pelican site
        run: |
          pelican content -s publishconf.py -t pelican-themes/pelican-bootstrap3 -o output

      # --- GitHub Pages에 배포 ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }} 

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: ./output 
          publish_branch: gh-pages 
          cname: none 